- CHANGELOG.md
- package.json
- src/index.js
So that contexture works! :)
See this line:
https://github.com/smartprocure/contexture/blob/master/src/index.js#L29
> Returning an object with a types property

- CHANGELOG.md
- README.md
- package.json
- src/default-types/mongoId.js
- src/index.js
- test/mongoId.js
> Using native mongo

- CHANGELOG.md
- package.json
- src/example-types/default.js
- src/example-types/exists.js
- src/example-types/mongoId.js
- src/example-types/results.js
- src/index.js
- test/example-types/mongoId.js
Add `data.values` support to mongoId (as an $in)
> Add values support to mongoId

- CHANGELOG.md
- package.json
- src/example-types/date.js
- src/example-types/results.js
- src/index.js
- test/example-types/text.js
Throw if the collection is not there
> Throw exception if collection is not found in db

- CHANGELOG.md
- package.json
- src/index.js
Fix bluebird regression and temporarily disable missing collection check
> Fix bluebird regression and temporarily disable missing collection check

- CHANGELOG.md
- package.json
- src/example-types/mongoId.js
- test/example-types/mongoId.js
> Extending the mongoId type to use exclude

- CHANGELOG.md
- package.json
- src/example-types/mongoId.js
- test/example-types/mongoId.js
Fix issue with exclude and single value
> refactoring

- CHANGELOG.md
- package.json
- src/example-types/exists.js
- src/example-types/facet.js
- src/example-types/mongoId.js
- src/example-types/number.js
- src/example-types/results.js
- src/example-types/text.js
- test/example-types/mongoId.js
- test/example-types/text.js
> kill data and config

- CHANGELOG.md
- package.json
- src/example-types/results.js
> Contexture is at 0.2.1, not 0.4.0 👀

- CHANGELOG.md
- package.json
- src/example-types/text.js
Fixed `Error: Failed running search for results (results) at result: MongoError: $and/$or/$nor must be a nonempty array`
> Fixed empty array on $or

- .circleci/config.yml
Ensuring we use Node 9 on our builds
> Ensuring we use Node 9 on our builds

- CHANGELOG.md
- README.md
- package.json
- src/example-types/statistical.js
- test/example-types/statistical.js
> Statistical type

- CHANGELOG.md
- package.json
- src/example-types/facet.js
I'll change the version after https://github.com/smartprocure/contexture-mongo/pull/23 is merged
> Unlimited facet

- .eslintrc
- CHANGELOG.md
- package.json
- src/example-types/statistical.js
- test/example-types/statistical.js
> Changed the statistical type so it doesn't return an array

- CHANGELOG.md
- package.json
- src/example-types/facet.js
- src/example-types/number.js
- test/example-types/date.js
- test/example-types/exists.js
- test/example-types/facet.js
- test/example-types/mongoId.js
- test/example-types/number.js
- test/example-types/statistical.js
- test/example-types/text.js
> S'more tests

- CHANGELOG.md
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
* Add array support for `facet` example type.
> Add array support to facet example type

- CHANGELOG.md
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
* Add support for facet optionsFilter
* Cleanup changelog
> Facet options filter

- CHANGELOG.md
- package.json
- src/example-types/statistical.js
- test/example-types/statistical.js
* Fix bug in `statistical` when there are no results
> Empty stats bug

- CHANGELOG.md
- package.json
- src/example-types/number.js
- test/example-types/number.js
Handle some edge cases including empty string.
> Handle edge cases around number type.

- CHANGELOG.md
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
Added support for Mongo ObjectIDs to the facet example type.
> Added isMongoId support to facet

- CHANGELOG.md
- package.json
- src/example-types/results.js
The Results type now allows unlimited results by setting pageSize to 0.
> 0.7.1: Unlimited Results

- CHANGELOG.md
- package.json
- src/example-types/tagsText.js
> add tagsText example type

- CHANGELOG.md
- package.json
- src/example-types/tagsText.js
> Fix typo on `tagsText` example type

- CHANGELOG.md
- package.json
- src/example-types/results.js
- test/example-types/results.js
- Adds `unwind` as part of the `populate` config section so it converts the populated values from array of single object to an object.
> Add unwind to populate config

- CHANGELOG.md
- package.json
- src/example-types/results.js
- test/example-types/results.js
Add the preserveNullAndEmptyArrays to the unwind so we do not "lose" rows after the unwind stage.
> Add "preserveNullAndEmptyArrays" to the $unwind

- CHANGELOG.md
- package.json
- src/example-types/results.js
- test/example-types/results.js
> Fix $unwind bug.

- CHANGELOG.md
- package.json
- src/example-types/text.js
> Cleanup hasValue

- CHANGELOG.md
- package.json
- src/example-types/dateHistogram.js
- test/example-types/dateHistogram.js
[DateHistogram] Fix key timestamp bug
> [DateHistogram] Fix key timestamp bug

- CHANGELOG.md
- package.json
- test/example-types/results.js
good thing it was already working 🙃
> Add a test case for not having more

- .gitignore
- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
> feat: add an unwind option

- CHANGELOG.md
- package.json
- src/example-types/facet.js
> fix: facet cardinality

- package-lock.json
- package.json
- test/example-types/dateHistogram.js
* Use `mongodb-memory-server` for date histogram tests.
* Mongodb should be a peer dep.
> Use mongodb-memory-server. Mongodb peer dep.

- .circleci/config.yml
- CHANGELOG.md
- integration-test/example-types/textAndMongoId.js
- package-lock.json
- package.json
- src/example-types/facet.js
- test/example-types/dateHistogram.js
> perf: improve facet pipeline performance

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
> test: add pipeline tests

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/bool.js
- src/example-types/exists.js
- test/example-types/bool.js
- test/example-types/exists.js
- Add bool example type with `falsy` support (which just does `$ne: true` on the field)
- Add tests for the bool example type
> Add bool example type and change exists 

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/date.js
- test/example-types/date.js
Support passing a timezone for rolling dates.
> Support passing a timezone for rolling dates.

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/date.js
> New rolling date ranges.

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/facet.js
- test/example-types/facet.js
Fix 'exclude mode' bug for facet type
Fix boolean values zero count search bug for facet type
> Fix the bug of 'exclude mode' and boolean values

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/results.js
- test/example-types/results.js
* Add populate field option to indicate that the join field has many records and adjust sort, skip, limit order in aggregation pipeline
> Results `populate` support for has many on unwind

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/results.js
Fix for count query when has many is present on a "populate" field
> Fix for count query when has many is present on a "populate" field

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/date.js
add next18Months rolling date type options
> add next18Months rolling date type options

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/results.js
- test/example-types/results.js
use the wrong restore command removed the test. will add test tomorrow
> Populate fix

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/results.js
- test/example-types/results.js
Fixes #99 
* as discussed on Slack, we want to weaken this util to not check anything if the node has no includes, as that's including everything and that's the most one can include
> feature/99 - update to checkPopulate util

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/results.js
- test/example-types/results.js
Fixes #99 
* as discussed on Slack
> Feature/99 - account for `as` in `checkPopulate`

- CHANGELOG.md
- package-lock.json
- package.json
- src/example-types/date.js
> feat: add last1 day/last1 hour date math

- CHANGELOG.md
- package-lock.json
- package.json
- src/index.js
Use `debug` to see request query and response and timings.
```
DEBUG=contexture:* DEBUG_DEPTH=100 npm start
```
> Debug queries

- CHANGELOG.md
- package-lock.json
- package.json
> Updated peerDependency to reflect current requirements
